RMX2020: Disable mediatek usb gadget rc prebuilt via soong config bool
Set use_custom_usb_gadget_rc soong config variable to disable
the init.mt6768.usb.rc prebuilt_etc from
hardware/mediatek/aidl/gadget, which was conflicting with the
device tree's own copy of the same module.

Fixes:
      error: hardware/mediatek/aidl/gadget
Android.bp:73:1: module "init.mt6768.usb.rc" variant "android_vendor_arm64_armv8-2a-dotprod_cortex-a75": found in multiple namespaces(device/realme/RMX2020 and hardware/mediatek) when including in vendor partition

Signed-off-by: Koushik Dey <kousickdey3@gmail.com>